import Footer from "@/components/footer";
import Head from "next/head";
import { Inter } from 'next/font/google';
import styles from "@/styles/Home.module.css";
const inter = Inter({ subsets: ['latin'] });
import NavBar from "@/components/nav";


export default function Layout({ children }) {
    return (
        <>
            <Head>
                <title>OC App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <NavBar />
            <main className={`${styles.main} ${inter.className}`}>
                {children}
            </main>
            <Footer />
        </>
    )
}